### ISSUE TITLE
Only For Windows 

### ISSUE THREAD

**Issue by Burnou7** [mariiaan/cmdplay-pp#1]
I was wandering if you only made this specifically for windows/windows terminal. If not will this work in any linux distros and will it also work ok with certain terminal emulators like alacritty or kitty

**Comment by mariiaan** [comment]
The way it's written now, it would theoratically support linux, also macOS. You would only need to link the executable against bass and FFmpeg for those platforms. I will try it for linux soon.

**Comment by Burnou7** [comment]
Thanks
